// <auto-generated />
namespace MasterDetail.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class WORowVersion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WORowVersion));
        
        string IMigrationMetadata.Id
        {
            get { return "201602252219262_WORowVersion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
